# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Testnet Bridge Tasks - Build and deploy Function App

on:
  push:
    branches:
      - testnet-new
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME_ETH: testnet-eth-bridge-tasks    # set this to your application's name
  AZURE_FUNCTIONAPP_NAME_BSC: testnet-bsc-bridge-tasks    # set this to your application's name
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'serverless/bridge-tasks' # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '12.x' # set this to the node version to use (supports 8.x, 10.x, 12.x)

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:


    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v2

    - name: Setup Node ${{ env.NODE_VERSION }} Environment
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: 'Resolve Project Dependencies Using Npm'
      shell: pwsh
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        npm install
        npm run build:production
        npm run test --if-present
        popd

    - name: 'Run Azure Functions Action ETH'
      uses: Azure/functions-action@v1
      id: bridgeETHFA
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME_ETH }}
        slot-name: 'staging'
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_61bbb1a27cf444349984addfa45203cf }}

    - name: 'Run Azure Functions Action BSC'
      uses: Azure/functions-action@v1
      id: bridgeBSCFA
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME_BSC }}
        slot-name: 'staging'
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_BSC }}
