# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: BSC Testnet API Deploy

on:
  push:
    branches:
      - testnet
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to registry
        uses: docker/login-action@v1
        with:
          registry: https://enigmampc.azurecr.io/
          username: ${{ secrets.AzureAppService_ContainerUsername_58f109b8139446ffb3cf77e3e55afc6b }}
          password: ${{ secrets.AzureAppService_ContainerPassword_03fc8fb1abeb4694b243af51e5b96215 }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: enigmampc.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_58f109b8139446ffb3cf77e3e55afc6b }}/bridge/backend-test:${{ github.sha }}
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'bridge-bsc-backend-testnet'
          slot-name: 'production'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_3b1e57055dd24fb28c2491ad8113986c }}
          images: 'enigmampc.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_58f109b8139446ffb3cf77e3e55afc6b }}/bridge/backend-test:${{ github.sha }}'